name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Secret Presence
        run: |
          if [ "${{ secrets.AWS_ACCESS_KEY_ID }}" != "" ]; then
            echo "AWS_ACCESS_KEY_ID is set"
          else
            echo "AWS_ACCESS_KEY_ID is not set"
          fi
          if [ "${{ secrets.AWS_SECRET_ACCESS_KEY }}" != "" ]; then
            echo "AWS_SECRET_ACCESS_KEY is set"
          else
            echo "AWS_SECRET_ACCESS_KEY is not set"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.MY_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }} # Use Git SHA as image tag
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
